name: opensearch-dashboards
base: core24

version: '2.19.2'

summary: 'OpenSearch Dashboards: community-driven OpenSearch visualization suite.'
description: |
    OpenSearch Dashboard is a community-driven, Apache 2.0-licensed open source
    user interface that lets you visualize your OpenSearch data and run and scale
    your OpenSearch clusters.

grade: stable

confinement: strict

platforms:
  amd64:


system-usernames:
  snap_daemon: shared


slots:
  logs:
    interface: content
    source:
      read:
        - $SNAP_COMMON/var/log/opensearch-dashboards

hooks:
  install:
    plugs:
      - network
      - network-bind
    environment:
      OPS_ROOT: ${SNAP_CURRENT}/opt/opensearch-dashboards


environment:
  SNAP_CURRENT: /snap/opensearch-dashboards/current
  SNAP_DATA_CURRENT: /var/snap/opensearch-dashboards/current

  SNAP_LOG_DIR: ${SNAP_COMMON}/ops/snap/logs

  OPS_ROOT: ${SNAP_CURRENT}/opt/opensearch-dashboards


  # Read-only spaces -- executables

  OPENSEARCH_DASHBOARDS_RO_HOME: ${SNAP_CURRENT}/usr/share/opensearch-dashboards
  OPENSEARCH_DASHBOARDS_BIN: ${OPENSEARCH_DASHBOARDS_RO_HOME}/bin
  OPENSEARCH_DASHBOARDS_DEPS_BIN: ${SNAP_CURRENT}/usr/bin
  NODE_HOME: ${OPENSEARCH_DASHBOARDS_RO_HOME}/node

  # Read-write spaces

  OPENSEARCH_DASHBOARDS_RW_HOME: ${SNAP_DATA_CURRENT}/usr/share/opensearch-dashboards
  OPENSEARCH_DASHBOARDS_PATH_CONF: ${SNAP_DATA_CURRENT}/etc/opensearch-dashboards

  OPENSEARCH_DASHBOARDS_VARLOG: ${SNAP_COMMON}/var/log/opensearch-dashboards
  OPENSEARCH_DASHBOARDS_VARLIB: ${SNAP_COMMON}/var/lib/opensearch-dashboards
  OPENSEARCH_DASHBOARDS_TMPDIR: ${SNAP_COMMON}/usr/share/tmp


apps:
  opensearch-dashboards-daemon:
    daemon: simple
    install-mode: disable
    command: opt/opensearch-dashboards/start.sh
    restart-condition: always
    restart-delay: 20s
    plugs:
      - network
      - network-bind


parts:
  dependencies:
    plugin: nil
    stage-snaps:
      - yq
    stage-packages:
      - curl
      - util-linux
      - python3

  wrapper-scripts:
    plugin: nil
    source: ./scripts
    source-type: local
    override-build: |
      target_dir="${CRAFT_PART_INSTALL}/opt/opensearch-dashboards"
      mkdir -p "${target_dir}"
      cp -r wrappers/. "${target_dir}"

  helper-scripts:
    plugin: nil
    source: .
    source-type: local
    override-build: |
      target_dir="${CRAFT_PART_INSTALL}/opt/opensearch-dashboards"
      mkdir -p "${target_dir}"
      cp -r helpers/ "${target_dir}/helpers"

  nodejs:
    plugin: nil
    override-build: |
      snap install node --channel=18/stable --classic

  opensearch-build:
    after:
    - dependencies
    plugin: nil
    source: https://github.com/opensearch-project/opensearch-build
    source-type: git
    source-tag: 2.19.2
    source-depth: 1
    build-packages:
      - python3.12-venv
      - jq
    override-build: |
      apt-get update
      version="$(craftctl get version)"
      LP_VERSION_TAG="lp-v${version}.0"
      MANIFEST_FILE="${CRAFT_PART_BUILD}/manifests/${version}/opensearch-dashboards-${version}.yml"

      # remove functionalTestDashboards plugin from manifest
      yq -i 'del(.components[] | select(.name == "functionalTestDashboards"))' "${MANIFEST_FILE}"
      
      awk '/repository: https:\/\/github.com\/opensearch-project\// { print tolower($0); next } { print }' "${MANIFEST_FILE}" > tmp && mv tmp "${MANIFEST_FILE}"
      sed -i -E 's|https://github\.com/opensearch-project/([^[:space:]/]+)\.git|https://git.launchpad.net/\1|g' "${MANIFEST_FILE}"

      # replace all tags with lp-v${version}.0
      sed -i "s|ref: tags/${version}.0|ref: tags/${LP_VERSION_TAG}|g" "${MANIFEST_FILE}"

      # Create build user
      BUILDER_HOME="/home/opensearch"
      BASE_BUILD_DIR="${BUILDER_HOME}/opensearch-build"
      useradd -m -d "${BUILDER_HOME}" opensearch
      mkdir -p "${BASE_BUILD_DIR}"
      
      # create dummy nvm.sh and nvm bin which do nothing (opensearch-dashboards build scripts expect nvm)
      echo '#!/bin/sh' > /nvm.sh
      echo 'true' >> /nvm.sh
      chmod +x /nvm.sh

      mkdir -p /opt/dummybin
      echo '#!/bin/sh' > /opt/dummybin/nvm
      echo 'true' >> /opt/dummybin/nvm
      chmod -R 755 /opt/dummybin

      echo 'export PATH="/opt/dummybin:$PATH"' >> ${BUILDER_HOME}/.profile

      # Copy repo content
      shopt -s dotglob
      cp -r "${CRAFT_PART_BUILD}"/* "${BASE_BUILD_DIR}"
      shopt -u dotglob
      chown -R opensearch:opensearch "${BASE_BUILD_DIR}"

      # Build and assemble
      manifest="${BASE_BUILD_DIR}/manifests/${version}/opensearch-dashboards-${version}.yml"
      cmd="cd ${BASE_BUILD_DIR}
      python3 -m venv venv
      . venv/bin/activate
      pip install pipenv
      export PIPENV_PIPFILE=${CRAFT_PART_BUILD}/Pipfile
      python3 -m pipenv install --deploy --system
      bash build.sh '${manifest}'
      bash assemble.sh tar/builds/opensearch-dashboards/manifest.yml"
      su - opensearch -c "${cmd}"

      # Extract and arrange
      archive="${BASE_BUILD_DIR}/tar/dist/opensearch-dashboards/opensearch-dashboards-${version}-linux-x64.tar.gz"
      tar -xzf "${archive}" -C "${CRAFT_PART_INSTALL}/" --strip-components=1

      mkdir -p "${CRAFT_PART_INSTALL}/usr/share/opensearch-dashboards"
      mkdir -p "${CRAFT_PART_INSTALL}/etc/opensearch-dashboards/"

      mv "${CRAFT_PART_INSTALL}"/config/* "${CRAFT_PART_INSTALL}/etc/opensearch-dashboards/"
      declare -a resources=(
        assets  bin  data  manifest.yml  node  node_modules  package.json  plugins  src LICENSE.txt  NOTICE.txt  README.txt
      )

      for res in "${resources[@]}"; do
          mv "${CRAFT_PART_INSTALL}/${res}" "${CRAFT_PART_INSTALL}/usr/share/opensearch-dashboards/"
      done
      chmod -R 755 "${CRAFT_PART_INSTALL}/usr/share/opensearch-dashboards/bin"

