name: opensearch-dashboards
base: core22

version: '2.10.0'

summary: 'OpenSearch Dashboards: community-driven OpenSearch visualization suite.'
description: |
    OpenSearch Dashboard is a community-driven, Apache 2.0-licensed open source 
    user interface that lets you visualize your OpenSearch data and run and scale
    your OpenSearch clusters.

grade: stable

confinement: strict

architectures:
  - build-on: amd64


system-usernames:
  snap_daemon: shared


hooks:
  install:
    plugs:
      - network
      - network-bind
    environment:
      OPS_ROOT: ${SNAP_CURRENT}/opt/opensearch-dashboards


environment:
  SNAP_CURRENT: /snap/opensearch-dashboards/current
  SNAP_DATA_CURRENT: /var/snap/opensearch-dashboards/current

  SNAP_LOG_DIR: ${SNAP_COMMON}/ops/snap/logs

  OPS_ROOT: ${SNAP_CURRENT}/opt/opensearch


  # Read-only spaces -- executables

  OPENSEARCH_DASHBOARDS_RO_HOME: ${SNAP_CURRENT}/usr/share/opensearch-dashboards
  OPENSEARCH_DASHBOARDS_BIN: ${OPENSEARCH_DASHBOARDS_RO_HOME}/bin
  NODE_HOME: ${OPENSEARCH_DASHBOARDS_RO_HOME}/node

  # Read-write spaces

  OPENSEARCH_DASHBOARDS_RW_HOME: ${SNAP_DATA_CURRENT}/usr/share/opensearch-dashboards
  OPENSEARCH_DASHBOARDS_PATH_CONF: ${SNAP_DATA_CURRENT}/etc/opensearch-dashboards

  OPENSEARCH_DASHBOARDS_VARLOG: ${SNAP_COMMON}/var/log/opensearch-dashboards
  OPENSEARCH_DASHBOARDS_VARLIB: ${SNAP_COMMON}/var/lib/opensearch-dashboards
  OPENSEARCH_DASHBOARDS_TMPDIR: ${SNAP_COMMON}/usr/share/tmp


apps:
  daemon:
    daemon: simple
    install-mode: disable
    command: opt/opensearch-dashboards/start.sh
    restart-condition: always
    restart-delay: 20s
    plugs:
      - network
      - network-bind

parts:
  dependencies:
    plugin: nil
    stage-snaps:
      - yq
    stage-packages:
      - util-linux
      - curl

  wrapper-scripts:
    plugin: nil
    source: ./scripts
    source-type: local
    override-build: |
      target_dir="${CRAFT_PART_INSTALL}/opt/opensearch-dashboards"
      mkdir -p "${target_dir}"
      cp -r wrappers/. "${target_dir}"

  helper-scripts:
    plugin: nil
    source: .
    source-type: local
    override-build: |
      target_dir="${CRAFT_PART_INSTALL}/opt/opensearch-dashboards"
      mkdir -p "${target_dir}"
      cp -r helpers/ "${target_dir}/helpers"

  nodejs:
    plugin: nil
    override-build: |
      snap install node --channel=18/stable --classic

  opensearch-dashboards:
    plugin: npm
    npm-include-node: true
    npm-node-version: 18.16.0
    source: .
    override-build: |
      version="$(craftctl get version)"
      archive="opensearch-dashboards-${version}-linux-x64.tar.gz"

      # Download Opensearch Dashboards
      url="https://artifacts.opensearch.org/releases/bundle/opensearch-dashboards/${version}/${archive}"
      curl  -L -o "${archive}" "${url}"

      # Extract and arrange
      tar -xzvf "${archive}" -C "${CRAFT_PART_INSTALL}/" --strip-components=1

      mkdir -p "${CRAFT_PART_INSTALL}/usr/share/opensearch-dashboards"

      mkdir -p "${CRAFT_PART_INSTALL}/etc/opensearch-dashboards/"
      mv "${CRAFT_PART_INSTALL}"/config/* "${CRAFT_PART_INSTALL}/etc/opensearch-dashboards/"

      declare -a resources=(
        assets  bin  data  manifest.yml  node  node_modules  package.json  plugins  src LICENSE.txt  NOTICE.txt  README.txt
      )

      for res in "${resources[@]}"; do
          mv "${CRAFT_PART_INSTALL}/${res}" "${CRAFT_PART_INSTALL}/usr/share/opensearch-dashboards/"
      done
      chmod -R 755 "${CRAFT_PART_INSTALL}/usr/share/opensearch-dashboards/bin"

      # Final clean-up
      rm "${archive}"
