name: wazuh-dashboard
base: core24

version: '4.8.2'

summary: OpenSearch Dashboards with additional changes for easier use alongside Wazuh.
description: |
    Wazuh Dashboard is a community-driven, Apache 2.0-licensed open source 
    user interface that lets you visualize your Wazuh data and run and scale
    your Wazuh clusters.

grade: stable

confinement: strict

platforms:
  amd64:

package-repositories:
  - type: apt
    components: [main]
    suites: [jammy]
    key-id: 6676E3F1A76ADBE4488944BF7D1A96D4BF78C79E
    url: https://ppa.launchpadcontent.net/data-platform/prometheus-kibana-exporter/ubuntu
# TODO: build from sources
  - type: apt
    components: [main]
    suites: [stable]
    key-id: 0DCFCA5547B19D2A6099506096B3EE5F29111145
    key-server: https://packages.wazuh.com/key/GPG-KEY-WAZUH
    url: https://packages.wazuh.com/4.x/apt/

system-usernames:
  snap_daemon: shared


slots:
  logs:
    interface: content
    source:
      read:
        - $SNAP_COMMON/var/log/wazuh-dashboard

hooks:
  install:
    plugs:
      - network
      - network-bind
    environment:
      OPS_ROOT: ${SNAP_CURRENT}/opt/opensearch-dashboards


environment:
  SNAP_CURRENT: /snap/wazuh-dashboard/current
  SNAP_DATA_CURRENT: /var/snap/wazuh-dashboard/current

  SNAP_LOG_DIR: ${SNAP_COMMON}/ops/snap/logs

  OPS_ROOT: ${SNAP_CURRENT}/opt/opensearch-dashboards


  # Read-only spaces -- executables

  OPENSEARCH_DASHBOARDS_RO_HOME: ${SNAP_CURRENT}/usr/share/wazuh-dashboard
  OPENSEARCH_DASHBOARDS_BIN: ${OPENSEARCH_DASHBOARDS_RO_HOME}/bin
  OPENSEARCH_DASHBOARDS_DEPS_BIN: ${SNAP_CURRENT}/usr/bin
  NODE_HOME: ${OPENSEARCH_DASHBOARDS_RO_HOME}/node

  # Read-write spaces

  OPENSEARCH_DASHBOARDS_RW_HOME: ${SNAP_DATA_CURRENT}/usr/share/wazuh-dashboard
  OPENSEARCH_DASHBOARDS_PATH_CONF: ${SNAP_DATA_CURRENT}/etc/wazuh-dashboard

  OPENSEARCH_DASHBOARDS_VARLOG: ${SNAP_COMMON}/var/log/wazuh-dashboard
  OPENSEARCH_DASHBOARDS_VARLIB: ${SNAP_COMMON}/var/lib/wazuh-dashboard
  OPENSEARCH_DASHBOARDS_TMPDIR: ${SNAP_COMMON}/usr/share/tmp


apps:
  opensearch-dashboards-daemon:
    daemon: simple
    install-mode: disable
    command: opt/opensearch-dashboards/start.sh
    restart-condition: always
    restart-delay: 20s
    plugs:
      - network
      - network-bind

  kibana-exporter-daemon:
    daemon: simple
    install-mode: disable
    command: opt/opensearch-dashboards/start-exporter.sh
    restart-condition: always
    restart-delay: 5s
    plugs:
      - network
      - network-bind


parts:
  dependencies:
    plugin: nil
    stage-snaps:
      - yq
    stage-packages:
      - util-linux
      - curl
      - prometheus-kibana-exporter

  wrapper-scripts:
    plugin: nil
    source: ./scripts
    source-type: local
    override-build: |
      target_dir="${CRAFT_PART_INSTALL}/opt/opensearch-dashboards"
      mkdir -p "${target_dir}"
      cp -r wrappers/. "${target_dir}"

  helper-scripts:
    plugin: nil
    source: .
    source-type: local
    override-build: |
      target_dir="${CRAFT_PART_INSTALL}/opt/opensearch-dashboards"
      mkdir -p "${target_dir}"
      cp -r helpers/ "${target_dir}/helpers"

  nodejs:
    plugin: nil
    override-build: |
      snap install node --channel=18/stable --classic

  wazuh-dashboard:
    plugin: nil
    build-packages:
      - apt-transport-https
      - gnupg
    stage-packages:
      - wazuh-dashboard
    override-stage: |
      craftctl default
      sed -i -e 's/^\([^#].*\)/# \1/g' etc/wazuh-dashboard/opensearch_dashboards.yml
      cat <<EOT >> etc/wazuh-dashboard/opensearch_dashboards.yml
      opensearch.hosts: [https://localhost:9200]
      opensearch.ssl.verificationMode: none
      opensearch.username: kibanaserver
      opensearch.password: kibanaserver
      opensearch.requestHeadersWhitelist: [authorization, securitytenant]

      opensearch_security.multitenancy.enabled: true
      opensearch_security.multitenancy.tenants.preferred: [Private, Global]
      opensearch_security.readonly_mode.roles: [kibana_read_only]
      # Use this setting if you are running opensearch-dashboards without https
      opensearch_security.cookie.secure: false
      EOT
    override-prime: |
      craftctl default
      usr/share/wazuh-dashboard/bin/opensearch-dashboards-plugin install --allow-root anomalyDetectionDashboards
      chmod -R 755 usr/share/wazuh-dashboard
      find etc -type d -exec chmod +x {} \;
      chmod +r etc -R
