name: Publish to Snap Store

env:
  RELEASE: edge

on:
  pull_request:
  # push:
    # branches:
    #   - main

jobs:
  tests:
    name: Build and Run Tests
    uses: ./.github/workflows/ci.yaml

  release:
    name: Release snap
    needs:
      - tests
    uses: canonical/data-platform-workflows/.github/workflows/release_snap.yaml@v12.6.0
    with:
      channel: latest/edge
      artifact-prefix: ${{ needs.tests.outputs.artifact-prefix }}
    secrets:
      snap-store-token: ${{ secrets.SNAP_STORE_TOKEN }}
    permissions:
      contents: write  # Needed to create GitHub release
