#!/usr/bin/env bash

set -eux

mkdir -p "${OPENSEARCH_DASHBOARDS_PATH_CONF}/"
cp -r "${SNAP}/etc/" "${SNAP_DATA_CURRENT}/"

declare -a folders=("${OPENSEARCH_DASHBOARDS_HOME}" "${OPENSEARCH_DASHBOARDS_VARLIB}" "${OPENSEARCH_DASHBOARDS_VARLOG}" "${OPENSEARCH_DASHBOARDS_TMPDIR}")
for f in "${folders[@]}"; do
        mkdir -p $f
done

chmod -R 770 "${SNAP_DATA}"/*
chmod -R 770 "${SNAP_COMMON}"/*

chown -R snap_daemon "${SNAP_DATA}"/*
chown -R snap_daemon "${SNAP_COMMON}"/*
