#!/usr/bin/env bash

set -eux


source "${OPS_ROOT}"/helpers/io.sh
source "${OPS_ROOT}"/helpers/set-conf.sh


set -eux

function create_file_structure () {
    find /var/snap/wazuh-dashboard/current/ -type f
    echo $PWD
    mkdir -p "${OPENSEARCH_DASHBOARDS_PATH_CONF}/"
    cp -r "${SNAP}/etc/" "${SNAP_DATA_CURRENT}/"

    declare -a folders=("${OPENSEARCH_DASHBOARDS_RW_HOME}" "${OPENSEARCH_DASHBOARDS_VARLIB}" "${OPENSEARCH_DASHBOARDS_VARLOG}" "${OPENSEARCH_DASHBOARDS_TMPDIR}")
    for f in "${folders[@]}"; do
        add_folder "${f}" 770
    done
}


function set_base_config_props () {
    ls -la /var/snap/wazuh-dashboard/current/etc/*
    set_yaml_prop "${OPENSEARCH_DASHBOARDS_PATH_CONF}/opensearch_dashboards.yml" "path.data" "${OPENSEARCH_DASHBOARDS_VARLIB}"
}


create_file_structure
set_base_config_props


declare -a folders=("${SNAP_DATA}" ${SNAP_COMMON})
for f in "${folders[@]}"; do
    chown -R snap_daemon "${f}/"*
    chgrp root "${f}/"*
done
